#define O_BINARY 0
#include "qrsop.cxx"
#include "filepdu.cxx"
#include "rtc.cxx"
#include "flpdu.cxx"
#include "storage.cxx"
#include "verify.cxx"
#include "dimsen.cxx"
#include "dimsec.cxx"
#include "util.cxx" // zeromem, spacemem include "uniq.cxx" // uniq16, uniq8
#include "uniq.cxx"
#include "endian.cxx"
#include "trnsyn.cxx"
#include "pdu.cxx"
#include "pdata.cxx"
#include "aarj.cxx"
#include "aaac.cxx"
#include "aarq.cxx"
#include "deivr.cxx"
#include "socket.cxx"
#include "buffer.cxx"
#include "servertask.cxx"
